import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { chmod, cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

// `aie`, not `ai`: the short alias is deprecated in 0.2.0 and removed in 0.3.0.
execFileSync('pnpm', ['exec', 'aie', 'sync'], { stdio: 'inherit' });

const generatedBanner = (runtime) => `<!--

Generated by pnpm ai:sync (${runtime})
DO NOT EDIT.

-->\n\n`;

async function readMarkdownDirectory(directory) {
  const names = (await readdir(directory)).filter((name) => name.endsWith('.md')).sort();
  return Promise.all(
    names.map(async (name) => ({
      name: path.basename(name, '.md'),
      content: (await readFile(path.join(directory, name), 'utf8')).trim(),
    })),
  );
}

/** Reads a single scalar out of a file's YAML front matter. */
function frontMatterValue(content, key) {
  const match = new RegExp(`^${key}:\\s*(.+)$`, 'm').exec(content.split('---')[1] ?? '');
  return match?.[1]?.trim().replace(/^["']|["']$/g, '') ?? '';
}

/**
 * Renders CLAUDE.md.
 *
 * Rules are inlined because they govern every session. Agents are listed
 * rather than inlined: Claude Code loads their full definitions from
 * `.claude/agents/` when one is invoked, so repeating the bodies here would
 * spend context on every session to say the same thing twice. The Codex
 * artifacts are produced by the compiler and still inline agents, which is
 * the only way they are available to that runtime.
 */
async function renderRootInstructions(runtime) {
  const rules = await readMarkdownDirectory('.ai/rules');
  const agents = await readMarkdownDirectory('.ai/agents');
  const teams = existsSync('.ai/agent-teams') ? (await readdir('.ai/agent-teams')).sort() : [];

  const sections = [
    `# Blotato Comments — ${runtime} Guide`,
    '',
    'The `.ai/` directory is the source of truth. Generated runtime files are not edited directly.',
    '',
    '## Rules',
    '',
    ...rules.flatMap(({ name, content }) => [`### ${name}`, '', content, '']),
    '## Agents',
    '',
    'Invoke by name; full definitions are in `.claude/agents/`.',
    '',
    '| Agent | Model | Purpose |',
    '| ----- | ----- | ------- |',
    ...agents.map(
      ({ name, content }) =>
        `| \`${name}\` | ${frontMatterValue(content, 'model')} | ${frontMatterValue(content, 'description')} |`,
    ),
  ];

  if (teams.length > 0) {
    sections.push(
      '',
      '## Agent teams',
      '',
      'Read-only task forces run at a milestone rather than continuously. Each directory holds a launch prompt and seed tasks.',
      '',
      ...teams.map((team) => `- \`${team}\` — \`.claude/agent-teams/${team}/launch.md\``),
    );
  }

  return generatedBanner(runtime.toLowerCase()) + sections.join('\n').trim() + '\n';
}

async function generateRuntimeParityArtifacts() {
  // CLAUDE.md is re-rendered over the compiler's output; see the note on
  // renderRootInstructions for why the agents are a table rather than inlined.
  // AGENTS.md is left exactly as the compiler wrote it — since 0.2.0 the codex
  // adapter writes it at the repository root directly, where 0.1.x wrote it to
  // .codex/AGENTS.md and this script copied it up.
  await writeFile('CLAUDE.md', await renderRootInstructions('Claude'), 'utf8');

  await copyHooks('.codex/hooks');
  await copyHooks('.claude/hooks');
  await writeFile(
    '.codex/README.md',
    `${generatedBanner('codex')}# Generated Codex artifacts\n\nHooks are copied from .ai/hooks/. Runtime hook activation depends on the Codex host supporting the corresponding hook configuration.\n`,
    'utf8',
  );
  await cp('.ai/templates/claude-settings.json', '.claude/settings.json');
  await copyAgentTeams();
}

/**
 * Copies the hook scripts to a runtime directory.
 *
 * `.claude/hooks` used to be the compiler's, but 0.2.0 only emits hooks that
 * are declared in the manifest, and its hook model has four events —
 * pre-edit, post-edit, session-start, session-end. Two of this repository's
 * six hooks cannot be expressed in it: the commit guard is a pre-tool-use hook
 * matching Bash, and the verification hook runs on Stop. Declaring the other
 * four and hand-maintaining the rest would leave the set half-generated.
 *
 * So the scripts are copied here, exactly as `.codex/hooks` already was, and
 * `.ai/templates/claude-settings.json` stays the single place the wiring is
 * described. Without this the upgrade silently froze `.claude/hooks`: editing
 * a source hook would no longer reach the compiled one, and because sync no
 * longer writes those paths the CI drift check could not see it either.
 */
async function copyHooks(destinationDirectory) {
  await rm(destinationDirectory, { recursive: true, force: true });
  await mkdir(destinationDirectory, { recursive: true });
  const names = (await readdir('.ai/hooks')).filter((name) => name.endsWith('.sh')).sort();
  await Promise.all(
    names.map(async (name) => {
      const destination = path.join(destinationDirectory, name);
      await cp(path.join('.ai/hooks', name), destination);
      await chmod(destination, 0o755);
    }),
  );
}

/**
 * Agent teams are not a concept the compiler knows about, and the Claude
 * adapter replaces `.claude/` wholesale, so anything it does not generate is
 * lost on sync. Teams are therefore authored under `.ai/agent-teams/` like
 * every other source of truth and copied through afterwards, the same way
 * `.claude/settings.json` is.
 */
async function copyAgentTeams() {
  const source = '.ai/agent-teams';
  if (!existsSync(source)) return;
  await rm('.claude/agent-teams', { recursive: true, force: true });
  await cp(source, '.claude/agent-teams', { recursive: true });
}

await generateRuntimeParityArtifacts();

execFileSync(
  'pnpm',
  [
    'exec',
    'prettier',
    '--write',
    'CLAUDE.md',
    'AGENTS.md',
    '.codex/README.md',
    '.claude/settings.json',
  ],
  { stdio: 'inherit' },
);
