import { execFileSync } from 'node:child_process';
import { chmod, cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

execFileSync('pnpm', ['exec', 'ai', 'sync'], { stdio: 'inherit' });

const generatedBanner = (runtime) => `<!--

Generated by pnpm ai:sync (${runtime})
DO NOT EDIT.

-->\n\n`;

async function readMarkdownDirectory(directory) {
  const names = (await readdir(directory)).filter((name) => name.endsWith('.md')).sort();
  return Promise.all(names.map(async (name) => ({
    name: path.basename(name, '.md'),
    content: (await readFile(path.join(directory, name), 'utf8')).trim(),
  })));
}

async function renderRootInstructions(runtime) {
  const rules = await readMarkdownDirectory('.ai/rules');
  const agents = await readMarkdownDirectory('.ai/agents');
  const sections = [
    `# Blotato Comments — ${runtime} Guide`,
    '',
    'The `.ai/` directory is the source of truth. Generated runtime files are not edited directly.',
    '',
    '## Rules',
    '',
    ...rules.flatMap(({ name, content }) => [`### ${name}`, '', content, '']),
    '## Agents',
    '',
    ...agents.flatMap(({ name, content }) => [`### ${name}`, '', content, '']),
  ];
  return generatedBanner(runtime.toLowerCase()) + sections.join('\n').trim() + '\n';
}

async function generateRuntimeParityArtifacts() {
  await writeFile('CLAUDE.md', await renderRootInstructions('Claude'), 'utf8');
  await cp('.codex/AGENTS.md', 'AGENTS.md');

  await rm('.codex/hooks', { recursive: true, force: true });
  await mkdir('.codex/hooks', { recursive: true });
  const hookNames = (await readdir('.ai/hooks')).filter((name) => name.endsWith('.sh')).sort();
  await Promise.all(hookNames.map(async (name) => {
    const destination = path.join('.codex/hooks', name);
    await cp(path.join('.ai/hooks', name), destination);
    await chmod(destination, 0o755);
  }));
  await writeFile(
    '.codex/README.md',
    `${generatedBanner('codex')}# Generated Codex artifacts\n\nHooks are copied from .ai/hooks/. Runtime hook activation depends on the Codex host supporting the corresponding hook configuration.\n`,
    'utf8',
  );
  await cp('.ai/templates/claude-settings.json', '.claude/settings.json');
}

await generateRuntimeParityArtifacts();
