import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { chmod, cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

execFileSync('pnpm', ['exec', 'ai', 'sync'], { stdio: 'inherit' });

const generatedBanner = (runtime) => `<!--

Generated by pnpm ai:sync (${runtime})
DO NOT EDIT.

-->\n\n`;

async function readMarkdownDirectory(directory) {
  const names = (await readdir(directory)).filter((name) => name.endsWith('.md')).sort();
  return Promise.all(
    names.map(async (name) => ({
      name: path.basename(name, '.md'),
      content: (await readFile(path.join(directory, name), 'utf8')).trim(),
    })),
  );
}

/** Reads a single scalar out of a file's YAML front matter. */
function frontMatterValue(content, key) {
  const match = new RegExp(`^${key}:\\s*(.+)$`, 'm').exec(content.split('---')[1] ?? '');
  return match?.[1]?.trim().replace(/^["']|["']$/g, '') ?? '';
}

/**
 * Renders CLAUDE.md.
 *
 * Rules are inlined because they govern every session. Agents are listed
 * rather than inlined: Claude Code loads their full definitions from
 * `.claude/agents/` when one is invoked, so repeating the bodies here would
 * spend context on every session to say the same thing twice. The Codex
 * artifacts are produced by the compiler and still inline agents, which is
 * the only way they are available to that runtime.
 */
async function renderRootInstructions(runtime) {
  const rules = await readMarkdownDirectory('.ai/rules');
  const agents = await readMarkdownDirectory('.ai/agents');
  const teams = existsSync('.ai/agent-teams') ? (await readdir('.ai/agent-teams')).sort() : [];

  const sections = [
    `# Blotato Comments — ${runtime} Guide`,
    '',
    'The `.ai/` directory is the source of truth. Generated runtime files are not edited directly.',
    '',
    '## Rules',
    '',
    ...rules.flatMap(({ name, content }) => [`### ${name}`, '', content, '']),
    '## Agents',
    '',
    'Invoke by name; full definitions are in `.claude/agents/`.',
    '',
    '| Agent | Model | Purpose |',
    '| ----- | ----- | ------- |',
    ...agents.map(
      ({ name, content }) =>
        `| \`${name}\` | ${frontMatterValue(content, 'model')} | ${frontMatterValue(content, 'description')} |`,
    ),
  ];

  if (teams.length > 0) {
    sections.push(
      '',
      '## Agent teams',
      '',
      'Read-only task forces run at a milestone rather than continuously. Each directory holds a launch prompt and seed tasks.',
      '',
      ...teams.map((team) => `- \`${team}\` — \`.claude/agent-teams/${team}/launch.md\``),
    );
  }

  return generatedBanner(runtime.toLowerCase()) + sections.join('\n').trim() + '\n';
}

async function generateRuntimeParityArtifacts() {
  await writeFile('CLAUDE.md', await renderRootInstructions('Claude'), 'utf8');
  await cp('.codex/AGENTS.md', 'AGENTS.md');

  await rm('.codex/hooks', { recursive: true, force: true });
  await mkdir('.codex/hooks', { recursive: true });
  const hookNames = (await readdir('.ai/hooks')).filter((name) => name.endsWith('.sh')).sort();
  await Promise.all(
    hookNames.map(async (name) => {
      const destination = path.join('.codex/hooks', name);
      await cp(path.join('.ai/hooks', name), destination);
      await chmod(destination, 0o755);
    }),
  );
  await writeFile(
    '.codex/README.md',
    `${generatedBanner('codex')}# Generated Codex artifacts\n\nHooks are copied from .ai/hooks/. Runtime hook activation depends on the Codex host supporting the corresponding hook configuration.\n`,
    'utf8',
  );
  await cp('.ai/templates/claude-settings.json', '.claude/settings.json');
  await copyAgentTeams();
}

/**
 * Agent teams are not a concept the compiler knows about, and the Claude
 * adapter replaces `.claude/` wholesale, so anything it does not generate is
 * lost on sync. Teams are therefore authored under `.ai/agent-teams/` like
 * every other source of truth and copied through afterwards, the same way
 * `.claude/settings.json` is.
 */
async function copyAgentTeams() {
  const source = '.ai/agent-teams';
  if (!existsSync(source)) return;
  await rm('.claude/agent-teams', { recursive: true, force: true });
  await cp(source, '.claude/agent-teams', { recursive: true });
}

await generateRuntimeParityArtifacts();

execFileSync(
  'pnpm',
  [
    'exec',
    'prettier',
    '--write',
    'CLAUDE.md',
    'AGENTS.md',
    '.codex/AGENTS.md',
    '.codex/README.md',
    '.claude/settings.json',
  ],
  { stdio: 'inherit' },
);
